{% set name = "jupyter-cache" %}
{% set version = "0.4.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter-cache-{{ version }}.tar.gz
  sha256: 4c9b5431b1d320bc68440c21fa0a155bbeb29c5b979bef72222e244a7bcd54fc

build:
  number: 0
  noarch: python
  entry_points:
    - jcache = jupyter_cache.cli.commands.cmd_main:jcache
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - attrs
    - nbclient >=0.2,<0.6
    - nbdime
    - nbformat
    - python >=3.6
    - sqlalchemy >=1.3.12,<1.4
    - click-completion
    - click-log

test:
  imports:
    - jupyter_cache
    - jupyter_cache.cache
  commands:
    - pip check
    - jcache --help
  requires:
    - pip

about:
  home: https://github.com/ExecutableBookProject/jupyter-cache
  summary: A defined interface for working with a cache of jupyter notebooks.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anirrudh
    - chrisjsewell
    - conda-forge/jupyter-book
